const texts = [
  // `#TheForestDummy.jpg`,
  // `**DUMMY  IMAGE**`,
  `no-frame Light`,
  // `<div className="block">—---------------:-----------------------------------------::</div>`,
  // `no-frametime: present `,
  `no-frame #Intro.png`,
  `no-frame #Intro2.png`,
  `no-frame it was not a song, it was someone's laugh`,
  `no-frame someone who illuminated everything with her bright smile, so bright it could outshine our sun. Legend has it that it was her presence that brightens the ilo`,
  `no-frame Ilo, A planet , more like a STAR but habitable, couldnt express its beauty in words ,cant even draw`,
  `no-frame Ilo in Fall(Day Time in Ilo)`,
  `no-frame #ilo_day.png`,
  `no-frame Fall on Ilo is like Earth's day but far more mesmerizing. Everywhere you look, trees, flowers, and vibrant birds fill the landscape. In the dense forests, extraordinary creatures thrive. Picture a countryside brimming with farms, gardens, and forests under bright, warm weather, balanced perfectly by a cool, refreshing breeze. Its a harmonious, natural paradise.
    `,
  `no-frame Ilo in Risen(Night Time in Ilo)`,
  `no-frame #ilo_night.png`,
  `no-frame During Risen—the equivalent of night—the planet does not just grow dark. It glows with vibrant, aurora-like radiation. Every living being enlarges, except the Iloians (similar to humans on Earth). The wind smells like strawberry ice cream, and you can even see it with the naked eye. Imagine massive trees with colorful, glowing leaves, winds humming like melodies, and butterflies the size of humans. Its like a dreamlike paradise.`,
  `no-frame One would say its a heaven`,
  `no-frame Even this heavenly planet wouldnt be heavenly without this little girl, Cho`,
  `no-frame A beautiful black and blue butterfly sat on her head, gently moving its wings ,a glazier flame wings and adding to her joyful look.`,
  `no-frame She was happily playing with her small sheep.`,
  `#choIntro.png`,

  // `no-frame  She illuminated everything with her bright smile, so bright it could outshine the sun. A beautiful black and blue butterfly sat on her head, gently moving its wings ,a glazier flame wings and adding to her joyful look. She was happily playing with her small sheep.`,

  // `no-frame WELCOME to Planet ILO - it is a unique STAR where life thrives. Unlike Earth's sunrise and nightfall, Ilo experiences Risen and Fall.
  //   During Risen—the equivalent of night—the planet does not just grow dark. It glows with vibrant, aurora-like radiation. Every living being enlarges, except the Iloians (similar to humans on Earth). The wind smells like strawberry ice cream, and you can even see it with the naked eye. Imagine massive trees with colorful, glowing leaves, winds humming like melodies, and butterflies the size of humans. Its like a dreamlike paradise.
  //   `,

  // `no-frame Fall on Ilo is like Earth's day but far more mesmerizing. Everywhere you look, trees, flowers, and vibrant birds fill the landscape. In the dense forests, extraordinary creatures thrive. Picture a countryside brimming with farms, gardens, and forests under bright, warm weather, balanced perfectly by a cool, refreshing breeze. Its a harmonious, natural paradise.
  //   `,

  // `**Glazier flame- like fire made of ice breeze**`,
  // `**The farm exist in between two forest**`,
  `Twenty feet behind her`,
  ` a boy , about fifteen years old, stood in a meadow filled with flowers and butterflies. He watched his sister laugh and play while trying to cut the last log from a pile of fifty trees. Even though he was tired, he felt joy seeing her being happy. 
    But his smile slowly faded as he noticed other kids playing together far from there while his sister was alone.
    `,
  `#TheBoy.png`,
  `THE  BOY`,
  `#WholeMapOfCurrentScene.jpg`,
  `#TheFarm.jpg`,
  `THE  FARM`,
  `#currentLocationMap(TheFarm).jpg`,
  `CURRENT    LOCATION   TOP  VIEW`,

  `**He knows that she wants to play with other kids so badly, but she won’t **`,
  `He felt really hurt as he is the reason for  those kids not playing with her`,
  `He thought for a second and then`,
  `“Cho,” he called`,
  `“Aahhnnn?” she asked`,
  `He pointed at those kids`,
  `“why don’t you go there and play with them?”, he said`,
  `She looked at them playing cheerfully,
   saddened `,
  `Her face literally said  " i want to play with them"`,
  `But she suddenly changed her expression as she turned to answer her brother, like she was never saddened`,
  `“No, I’m going to play with Kiki,” she replied cheerfully and proceeded to chase her little sheep`,
  `He knew she was faking, so he decided to do something stupid. he sensed something behind her, he smirked`,
  `He picked a palm-sized piece of wood and threw it in her direction`,
  `The palm-sized wood fell on the something`,
  `thudd!!!`,
  `“BZZZZZZRRRAAAAHHHHH!”`,
  `Suddenly, a bee,green coloured,having moustache and spike on his hair, flew up from where the wood had landed`,

  `“Who the fuck decided to terminate me—aiizzzzz?”, the bee enraged`,
  // `**Yup the bee spoke**`,
  `Cho looked at the bee excitedly( she has never seen a bee speak)`,
  `“Hey👺… yo mean-looking monster, who sent you?” the bee demanded`,
  `Cho still looked at him excitedly`,
  // `“Must be that red-assed shithead” the bee muttered, looking down with its hand on its chin like its thinking`,
  `#TheBee.png`,
  `Meanwhile, Cho tried to capture the bee`,
  `The bee dodged her`,
  `“Hey👺… so you chose hands, huh?.......“Alright-iieeezzz, bbzzzz you wish,”,the bee`,

  `The bee started preparing its hands, posing like it was going to knock Cho down with a single punch`,
  `“Ah… wait… forgot my gloves,..you wait here” the bee said and flew away`,

  `**Five minutes later.**`,

  `The bee returned, hurt, with patches on its body, boxing gloves on, and its sting covered with sharp thing`,
  `Cho wasn’t there , bee got upset`,
  `“Hey, mean-looking monkey, where did you go?” the bee asked`,
  `“Scared, huh?” the bee smirked`,
  `Suddenly, a figure appeared behind the bee`,
  `The bee realized that something was standing behind it`,
  `“Triggas strategy, huh?” the bee smirked`,
  `(Triggas- Tiger in ilo)`,
  `Suddenly, a hand came to catch the bee`,
  `The bee dodged it and showed its sting like it was showing a middle finger`,
  `“Hm… noob,” the bee trolled`,
  `“Now you’re gonna pay for this,” the bee said, pointing at its wounds while dodging her`,
  `“You probably don’t know how my bee-ly looking face turned to shit,” the bee started blabbering`,
  `“I’ll tell you,” the bee started `,

  `**FLASHBACK – Five minutes before.**`,

  `The bee reached its home`,
  `“Honey, I’m home,” the bee said`,
  `“Who let you in?” the bee’s wife asked`,
  `“Uh…” the bee stood there, unable to utter a word`,
  `“What’s the time now?” the bee’s wife asked, cooking utensils in her hands (as weapons)`,
  `“I’m here to take equipment, honey. I’m not—” the bee started`,
  `“I told you not to come home before sunset, didn’t I?” the bee’s wife yelled while hitting the shit out of the bee`,

  `**PRESENT.**`,

  `“You’re the reason I enraged my beloved honey,” the bee said`,
  `“Mmmmmmmm… come here,” Cho said, trying hard to catch the bee`,
  `“Now prepare yourself to get hit by my stingy ass!” the bee shouted`,
  `Cho tried to grab it`,
  `The bee dodged`,
  `The bee spun, did some unnecessary stunts, and "HEE-YAA" finally pinched her nose`,
  `Cho’s nose swelled up like a tomato`,
  `she cried like a baby (she is a baby),she ran toward the boy, and the bee followed her`,

  `“Hm… kids,” the bee mocked`,
  `“Big broooooooo!” she cried`,
  `Meanwhile, the bee reached him before her , both bee and her brother were started talking like they know each other for years`,
  `“Hi, brother, what’s up?” the boy asked`,
  `“Fine, boy,” the bee replied`,
  `Cho got frustrated comically (not really angry)`,
  `Cho jumped and kicked the bee and her brother at the same time`,
  `Both fell, knocked down`,
  `The angered bee got up and said, “Now you did it, you little monkey!” The bee started chasing her`,
  `Cho started running toward those kids`,
  `“Raaahhhh!”`,
  `“Helpppppp!” Cho called`,
  `she fell right in front of the kids`,
  `“Now, you’re done,” the bee said, smiling`,
  `Suddenly, a bunch of bees rose from the ground`,
  `They all screamed`,
  `Even the green bee who was fighting cho got scared as he realized he was in the wrong territory`,
  `“Catch that green-assed fly!” one of the wrong territory bee ordered`,
  `They all started running around`,
  `the boy watched them as they playing(not exactly)`,
  `Now he hears people talking Far away from him.`,

  `People worked on their farms,chatting.`,
  `Suddenly a woman,who already looked like goddess ,with wearing that jerry colored saree ,damn... she is something that god cant even create,she looks like she is going to crush someone's heart,walked by them farm peoples`,
  `One of the farm women (P-1) called out:`,
  `They all know eachother`,
  `P-1: “Where did you buy this?”`,
  `other women were amazed by her beauty`,
  `The bywalker(goddess woman) paused, confused.
    Bywalker: “What, sister?”
    `,
  `P-1: “Your saree.”`,
  `The bywalker smiled shyly.
    Bywalker: “This? My husband bought it. Why, sister? Does it look good?”
    `,
  `P-1: “It looks gorgeous!”`,
  `The bywalker beamed.
    Bywalker: “Really?”
    `,
  `Another woman (P-2) joined the conversation.`,
  `P-2: “Hey neela,Shall we go to the market later?”`,
  `Bywalker: “Why, sister?”`,
  `P-2: “I haven’t bought anything for the festival yet.”`,
  `Bywalker: “Oh,.....I dont know. I’ll come if I’m free. `,
  `Okay, sisters, my husband’s waiting. See you at the festival!”`,
  `With that, she ran off happily, flapping her hands, dancing, and smiling.`,
  `p-3(in jealousy tone): "why p-2 , dont we look like a ilo'ian ? `,
  `p-2: why?`,
  `p-3: nothing, just wondering,  we were working together for a being, but you didnt ask any of us for a shopping`,
  `p-2: whyyy?.. last time we went for a shopping. you chose a shit colored saree and said it'll  look good on me,.... now... whenever i wear it, my kids close their nose and say " eww..stinks ma "(mimicked)`,
  `p-3: oh thats why you didnt wear it for any functions,haa?.....i thought you were saving it for the big occasion`,
  `they all started laughing`,
  `p-2(snapped) : you little  ^$*^%**^** jfsgjsgjs`,
  `The two other women watched bywalker go, puzzled.
    P-1: “Who does she call her husband? She is not married, is she?”
    P-2: “Now that you mention it… I do not know.”
    Both stared at her, confused, and said in unison:
    Both: “Mental.”
    `,
  `The boy had been watching the scene from that far. He put down his axe and rushed toward the saree woman.`,
  `Boy: “Hey… hey, red sister!”`,
  `She stopped and turned.
    : “What is it, brown boy?”,
    `,
  `He caught his breath.
    Boy: “Where did you buy this?” he asked, pointing to her saree.
    `,
  `Bywalker: “My husband bought it from the city. Why?”`,
  `The boy’s face fell.
    Boy: “city? ”
    `,
  `He turned and started walking away.`,
  `Bywalker: “Wait.”`,
  `He stopped.
    Bywalker: “For whom?”
    `,
  `Boy: “My sister”, he replied, looking down.`,
  `Bywalker: “Do you have money?” she asked, smiling.`,
  `Boy: “Not enough to buy something like your dress,” he admitted.`,
  `Bywalker: “I’ll help you get what you want,” she said.`,
  `His face illuminated.
    Boy: “Really?”
    `,
  `Bywalker: “Only if you do something for me,” she added with a playful smirk.`,
  `Boy: “What do you want me to do? I can cut, I can break, I can… I can do anything!” he said, eagerly.`,
  `Bywalker: “wait wait!...Tomorrow, by this time, wait here. I’ll tell you then.”`,
  `Boy: “Yes!” he shouted, filled with joy.`,
  `He flew off like a happy mosquito (not literally flying).`,
  `Then He realized He didnt thank her`,
  `He stopped and called The Red Saree and said "Thank Red Saree sister"`,
  `"No..No..No mention",she replied with a polite smile😅`,
  `Then He flew off`,
  `As he ran, a bywalker woman walked along the path. Nearby, three women stood watching the bywalker woman talking to a boy.`,
  `“Why did you talk to him?” one of the women asked.`,
  `“Why? Shouldn't I talk to him?” the bywalker woman replied.`,
  `“He’s that devil’s kid,” another woman said.`,
  `“He?…” The bywalker woman glanced at the boy, who was running happily. “Doesn’t look like it to me,”
  she replied.`,
  `He was happily running`,
  `........`,
  `......As we look further into the other side of the farm...exist another forest....`,
  `At the center of the warm, filled forest, a convoy of vehicles comes like a snake that swims in sewage. They are riding to the Village through The Farm`,

  `"Boss, you heard about that asteroid that fell a few days ago?" one of the people seated in
the back of a car asked.`,
  ` A man with a styled mustache, around 45, wearing sunglasses and a white shirt with dhotis,scrolling his phone, sitting in the front seat.`,
  `They call him "Boss."`,
  `The Boss  seated in the front, scrolling his mobile, did not notice the back-seater's words.`,
  `"Boss"`,
  `"Bosssssss," he repeated.`,

  `"What the fuck do you want?" the Boss snapped.`,

  `"Nothing, Boss," the back-seater backed off.`,

  `"Looks like Boss is busy doing something important," the back-seater whispered to another back-seater.`,

  `The driver peeked at the Boss's mobile to see what he was doing.`,

  `The Boss noticed.`,

  `"What the fuck are you looking at?" the Boss yelled, trying to slap him, but the driver dodged.`,

  `"Am I flashing my pee pee?" the Boss snapped. 👺`,
  `"Hehe, sorry, Boss," the driver stammered. `,

  `As we look closer at the Boss's mobile, the Boss is watching some naked dance shit, drooling.`,
  `… … . … … ..`,
  `Meanwhile the boy approached a pile of trees, he notices light glinted off a car emerging from the forest, followed by a convoy of vehicles
    His face changed as he senses like something bad about to happen, 
    `,
  `"Cho, come on, it’s time to go. We can come back tomorrow," he called out.`,
  `"Nooo," she protested, looking at him sweetly anger.`,
  `"Okay,im going ... they say  wolves love boiling kids in a hot soup and drin..." he joked, trying to scare her.`,
  `Before he could finish, she ran towards him.`,
  `"Haha, scaredy cat," he laughed.`,
  `Meanwhile the Boss watching them from the car`,
  `"Who is that brat?" the Boss asked his driver.`,
  `“Who, boss?” the driver replied.`,
  `“That brat!, you ^(^(^*#$#”, the Boss snapped.`,
  `"Him? You do not know him, boss?", the driver said with a hint of sarcasm`,
  `"Is he a fucking god ?" the Boss asked, annoyed as he took off his sunglasses and raises his leg.`,
  `"No, no, boss, I didn’t mean—" the driver stuttered.`,
  `the Boss kicked the driver out of the car.`,
  `"Go ask that brat what he’s doing on my fucking land," he ordered coldly.`,
  `The driver stood up, dusting off his shirt, glaring at the boy as if he were to blame. The driver’s eyes were filled with anger as he marched towards the boy. eventhough he looked anger, his body language says otherwise, he is afraid of that boy but he forced himself  not to show it`,
  `"What are you doing here?" the driver shouted.`,
  `"Just collecting wood," the boy answered calmly,looking down.`,
  `"who let you here ..Do you know who owns this land?" the driver asked sharply.`,
  `The boy looked innocently confused.`,
  `"Where are you taking this?" the driver,pointing those woods.`,
  `"To Jehan boss," the boy replied.`,
  `(Jehan is the rival of THE BOSS) `,
  `"What? Speak up, I didn’t hear you," the driver growled.`,
  `"To Jehan boss," the boy repeated, still looking down.`,
  `Anger flared in the driver’s eyes. “Bosss?!" he shouted, and then he hit the boy.`,
  `The boy fell to the ground.`,
  `“Boss? That jerk?!" the driver yelled`,
  ,
  `Then the driver pointing his finger at the Boss in the car and started ,"Look at him" ,"The Boss in the car gave a cold look that said, I’m the one ."..  "He is the only bo—", but was cut off.`,

  ` a sharp sound interrupted  him, he  started  yelping in pain and began to stagger around. He saw the cause of his pain: the little girl holding a stick, fury in her eyes.`,
  `He got hit by cho`,
  `"Don’t hurt my brother," she said firmly.`,
  `"you little brat,.." the driver growled.`,
  `She stared back at him with a fierce look.`,
  `“Who the hell are you? “, the driver growled. `,
  `
    As the driver moved toward her, the boy quickly stepped in. "Please, do not hurt my sister!" he pleaded. "You can hit me instead, but do not hurt her!" He held out the stick to the driver, his voice desperate.
    `,
  `The driver surprised, hesitated, looking at the stick, and slowly reached out to take it.`,
  `But just as he was about to grab it, a sudden loud sound scared him. He thought it was some kind of animal like a boar.`,
  `It was not. It was the Boss—standing half inside, half outside the car—laughing at them arrogantly, as if he owned the world.`,
  `"Come on, we need to meet “that boss”,’" the Boss said sarcastically, mocking the title.`,
  `"Yes, boss," the driver replied, flustered.`,
  `who are you calling "Boss",the Boss asked`,
  `"who else boss, its you only",the driver replied as scartching the place where cho hit`,
  `"GOOD",the Boss smiled `,
  `"If I see you here again, I do not know what I’ll do," the driver threatened, trying to scare the boy before going back into the car.`,
  `"If anyone sees them on my land again, cut them both up and feed them to Reema," the Boss ordered coldly.`,
  `"Yes, boss!" his men shouted together.`,
  `"Start the car, we’ve got work to do," the Boss commanded.`,
  `The boy’s eyes widened in fear, his heart racing. The anger in the little girl began to fade as her brother's tears softened her rage. She dropped the stick and hugged her brother's leg tightly.`,
  `The cars sped away, their engines roaring, and among them was a truck that stood out. As it moved, the truck trembled ominously, as though some kind of BEAST was caged within. soon the sound of the engines faded into the distance`,
  `The boy looked at cho `,
  `"sorry, big bro",looking down,cho cried`,
  `His sad face brightened as if nothing had happened.(he is trying to cheer her up)`,
  `See, Cho? They ran… cowards.Who are they messing with?" he joked, flexing his arms comically.`,
  `Cho looked at him surprisingly`,
  `"what?....i was acting...",the boy😆`,
  `"You’re so cool, big bro!" she said, her eyes wide with admiration (not knowing he is pretending).`,
  `“Well, let's go, before those cowards return,” he said.`,
  `“Mmm, big bro,” she replied.`,
  `
    With nearly 50kg of wood logs balanced on his head, he began to move.
    `,
  `"they will scold you big bro if we take these wo--",cho stopped `,
  `"what cho",the boy asked with a smile on his face`,
  `"Nothing Big Bro",cho replied happily`,
  `Both started walking Happily`,
  `The nearby children, once joyful, suddenly fell silent as the boy and his sister walked past. Cho waved at them cheerfully, smiling widely, but they looked scared, as if they had seen a ghost. Their eyes were fixed on the boy.`,
  `cho noticed that`,
  `MEANWHILE IN THE CAR`,
  `“Well, who was that brat?” the Boss asked the driver while lighting up his cigar.`,
  `“You…” the driver started again.`,
  `“You son of a…” the Boss picked up his gun from his hip pocket and pointed it at the driver.`,
  `“I’ll fucking gut you if you start with ‘You do not know, boss?’ again!” the driver snapped.`,
  `The driver side-eyed the gun, comically afraid.`,
  `“No, no, boss, I didn’t mean… I meant to say he is that devil’s kid. Don’t shoot me, boss!” the driver rushed to say, still fearful (comically).`,
  `“Oh,” the Boss said.`,
  `Suddenly, both the Boss and the driver realized the driver had taken his hands off the wheel as he surrendered  in his panic.`,
  `Both looked at each other, shock written on their faces, and then screamed  "aaaaHHHHHHHHH".The car started to tremble, descending into a moment of chaos.`,
  `SUDDEN FLIP CUT`,
  `After a little car-shaking moment, the driver’s face, which had earlier been like a tomato floating in water, now looked like it had been smashed by a punch from pigs.`,
  `The Boss wiped the driver’s bloodstains off his gun using a cloth torn from the driver’s clothes while the driver tended to his wounds, still driving.`,
  `“Mmm… what were you saying?” the Boss asked.`,
  `The driver looked at him but could not talk; his mouth was punctured.`,
  `
    “You dare to refuse my question?” the Boss said, glancing at his gun.
    `,
  `“Mmshdjsjd… Sjse,” the driver mumbled something unintelligible.`,
  `“Huhhh?” the Boss replied.`,
  `The driver looked at him again.`,
  `The Boss burst out laughing, almost choking on his amusement.`,
  `“Look at him, look at his stinky-ass nose!” the Boss exclaimed to the back seaters, still laughing.`,
  `“Come here, come here!” the Boss called to them. `,
  `“See?” he pointed at the driver’s nose.`,
  `They all laughed at the driver.`,
  `CAR STOPS`,
  `“What, you going to hit us”, the Boss joked. `,
  `“We’ve reached, boss,” the driver announced.`,
  `They all stopped laughing.`,
  `The Boss smirked.`,
  `“kK boys, get your ass up,” the Boss shouted.`,
  `“It’s money-plucking time,” he murmured, scratching his butt.`,
  `TRUCK TREMBLES AGAIN`,
  `“Feed that goddamn BEAST, you useless sons of sons!” the Boss raged.`,
  `“Yes, boss,” they replied.`,
  `Boss!!, ithukku onnum korachal illa (in english)`,
  `The Boss thinking about something seriously`,
  `**Could be That half naked shit**`,
  `"Boss,what should we do about that brat?",the driver`,
  `"huh?",the Boss as he didnt hear a word from the driver,he is still busy thinking about something `,
  `"that brat, Boss"`,
  `"what about him?"`,
  `"what should we do about him",the driver`,
  `"what should we do?",the Boss asked`,
  `"i dont know boss....i heard people talking...he roams around the village at night...people are afraid of him, even i.."`,
  `"Not only that. He was Your enemy's son as well",the driver added`,
  `"so?..",the Boss`,
  `"nothing boss,just saying"`,
  `"Aahhhh... I know... I know... I know. what... you're... trying to say....... There should be only one person people should be afraid of, right?", The Boss. `,
  `The driver confused, his face was like "is he fucking dumb?"`,
  `"Yes, i am" written in the Boss's face`,
  `"Did he just ignored  "your enemy's son" ",the driver murmured`,
  `"what?",the Boss`,
  `"Nothing Boss, ill take my leave",the driver`,
  `The driver moved from there`,
  `......`,
  `“Mm... devil’s son,the one who cheated death, huh,” the Boss smirked MENACINGLY, as if he was about to do what he had ordered his men to do in the farm(CUT THE BOY AND CHO).`,
  `**The look on him was so powerful that it sent us back in time.**`,
  `YEARS AGO................`,
  `A palace`,
  `A Home like a palace,  with a fountain at its center. Birds roamed freely inside, and a single tree near the fountain teemed with chirping birds. `,
  `It was filled with the soothing sounds of nature.`,
  `Inside that home, in a room on the first floor, a man, who appears to be a scientist, prayed hard while hearing the sound of his wife crying.`,
  `He couldnt hear her struggle`,
  `The scientist was expecting his FIRST? baby (The Boy, Cho's brother)`,
  `"Don't worry, sir, for your good heart, this baby will be....," said one of a palace maid `,
  `"please dont!! ..... go help them",he pleaded `,
  `Meanwhile other Palace workers at the  down stairs chatted excitedly about the baby’s birth.`,
  `Worker 1: “Do you think this baby will live?”`,
  // `** well,i wouldnt say it "Excitedly"**`,
  `Worker 2: “Who knows?”`,
  `Worker 3: “Even if it does not, they’re going to breed another one. Ha ha ha!” (cracked a joke).`,
  `Worker 4: “Shut up, idiot!” (bashed).`,
  `Worker 3: “What? Am I wrong?so far How many times? Five, right?”`,
  `Worker 4: “So?”`,
  `Worker 3: “Nothing, just saying.”`,
  `Worker 4: “Don’t make fun of something like this. You’re a woman; you should be the last person to laugh at something like this.”`,
  `Worker 2: “How can you make fun of their feelings? They fed you.”`,
  `Worker 1: “That too, you making fun of Mr.Rav’s family’s feelings.”`,
  `Worker 3: “wait ..wait... hold on a min----—”`,
  `A strong cry of a baby interrupted the talk.`,
  `Worker 1: “The baby is born!”, excited`,
  `They ran up the stairs.`,
  `worker 3 who was cracking  jokes , froze there like she saw a BEAST`,
  `Inside the room, the scientist comforted his wife. Her face was filled with joy as she leaned against his chest. He held the baby in his arms, both unable to contain their happiness as they have never even heard the sound of their baby,its their first time hearing their baby's cry. The room was filled with warmth and light and birds and flies.`,
  `As the room glowed with happiness, the atmosphere outside changed abruptly. Darkness enveloped everything, and a heavy silence fell. Movements slowed, as if time had paused.`,

  `BLANK… EVERYTHING BLACKED OUT.`,
  `Suddenly, a hurricane came, not a normal one, a hurricane of dead souls swept through the house. These souls, with claws, reached out to grab everyone nearby. In the eye of the Hurricane, the baby floated.`,
  // `A SUDDEN CUT`,
  `Outside the palace, everything appeared normal as if The Hurricane Appeared out of nowhere inside the Home.`,
  `Moments later,The hurricane gone so does the Home, the inside of the palace was in ruins—blood splattered on the walls, claw marks everywhere, furniture destroyed, and birds broken and lifeless.`,
  `The scientist and his wife, injured and devastated, searched desperately for the baby.`,
  `"Did you find my-",the wife asked as she struggling walking downstairs`,
  `"what are you doing here?", scientist`,
  `"shut uppp.... i have to see my baby",the wife cried`,
  `"ill find the baby, please dont come down . everything's ruined..you need rest", scientist`,
  `"i dont need rest, i just need my baby",the wife `,
  `she fainted`,
  `"sita", scientist yelled her name`,
  `scientist rushed towards her and caught before she fell and both seated`,
  `"what's happening..where is my baby",she (in lower voice as she had no energy in her)`,
  `"i dont know...i dont know....im  sorryy...i dont knowww",scientist cried`,
  `she wipes his tears with hands,he grabbed her tightly`,
  `He suddenly noticed baby like figure near the fountain`,
  `"wait here", scientist excitedly rushed towards the baby`,
  `The baby is found`,
  `But excitement in his face started to fade as the baby doesnt have any movement`,
  `He just froze there`,
  `"what happened... did you find the baby",the wife`,
  `Mr.Rav, she called`,
  `she got up and rushed towatds them,struggling`,
  `"what Rav",the wife`,
  `Then she finally  saw the baby`,

  `Dead.
    `,
  `Both scientist and his wife broke into pieces.......`,
  `They both cried so loudly that the sound of their pain was unbearable ,even the ILO started  crying (ILO  have never had rain)`,
  `Before the baby was born, ILO represented absolute peace, goodness, love, life, and every positive thing imaginable.`,
  `Even words like "hate," "jealousy," and "greed",,,etc simply did not exist there.`,
  `Now, everything is about to change, just as the rain became a part of ILO's weather.`,
  `This rain was painful even to ILO itself. In an attempt to extinguish the rain, which was a manifestation of pure pain, ILO emitted a powerful force.
The force was so immense that it sent us hurtling back to the present.`,
  `What happened after that will be revealed later.`,
  ` CUT  TO  PRESENT`,

  `"Wait.....DEAD ????"`,
  `
    PRESENT. 
    Time: around 7:30
    `,
  `A strong wind blew through the air. It didn’t smell like just any wind; it smelled sweet, like strawberry ice cream. The wind was so powerful it could lift an adult off the ground. The world around looked bright and colorful, like a beautiful light show.`,
  `The entire world transformed into a magnificent light show, like the auroras of the northern pole, but spanning the entire planet. Sweetness filled the air, and the warmth of light rising from the ground was so captivating that even the blind or those without a sense of smell would be entranced. Every bird, tree, and insect—except ILOians—grew into towering giants.`,
  `While the world around The boy became brighter and larger, the boy’s own world shrank and dimmed as he returned to his current home. There was nobody else. The house was not lively, but in the middle of a rundown, almost garbage-like house, he was cooking something delicious.`,
  `The battle between the scent of the food and the sweet fragrance of the world could shake the whole world.`,
  `He brought food to his little sister, who was sad and petting their sheep. When she smelled the food, her sad face illuminated with joy, and her eyes sparkled with happy tears.`,
  `"cho here's yo--"`,
  `she grabbed the food and started eating even before he finished the sentence`,
  `He was like "what happened just now"`,
  `He sat down with her and started eating`,
  `Both were sitting on folding cot`,
  `"How is it?",he asked`,
  `“Areweryoue gmadsaat me, big brother?” she asked(blaffed), her mouth full of food and snorting a little.`,
  `“Haaaaaaann?” he asked, confused but smiling.`,
  `“Are you mad at me?” she asked again, still sniffling.`,
  `“Eat slowly, Cho,” he said, tapping her head gently and giving her water.`,
  `While she drank, He gazed up at the sky, where the wind and asteroids drifted so beautifully, like a vast sea shimmering with colorful, glowing fish..`,
  `Suddenly, there was "BONKK", and he fell to the ground, dizzy and feeling like he had been knocked out.`,
  `His sister stood over him, holding a broomstick and smiling evil'ly. “Are you mad at me, big bro?” she firmly asked.`,
  `“Uhh…,” he mumbled, still dizzy from the bump.`,
  `"huuuhhhhhh??????",she screamed`,
  `He came back to senses`,
  `Then he jumped up and said, “I heard there’s going to be a fireworks festival in the village” He started eating like nothing happened.`,
  `She Realized What he meant`,
  `Her face suddenly went from anger to happy like a kitten.`,
  `She started eating again`,
  `"Food is so spicyy🤤 ,big bro",she devoured`,
  `"spice,aah??  , its sweet",he confused`,
  `"ah,,,sorry😅",she `,

  `“Trrk trrk, here take this yian(boy's name)!” she called to her little sheep.`,
  `The boy looked surprised and shocked. “Really?..” ah look`,
  `“What? I won’t give it to you! Bleh!” she teased.`,
  `“Ohh..I see,” he said`,

  `Now he started posing like he's going to  pull the sheep from the air magically.`,
  `He closed his eyes and—BOOM!—the sheep disappeared.`,
  `She isn't surprised. she just opened her arms,closed her eyes waiting for the sheep to come back, bouncing around and excited.(she knows he will undo whatever he just did)`,
  `But  Nothing happened. She opened one eye and saw him eating calmly.`,
  `Suddenly He began to sweat, feeling hot even in the cold night.`,
  `“Biggggg... Brother,” she said in a funny, scary voice.`,
  `He turned slowly, sensing trouble as she looked at him like a  little monster.`,
  `“Okay,..okay...ill  bring  kiki back... calm down, Cho. Why so serious?” he said with a confusingly smily face.😅`,
  `"Good", She turned back into her sweet self.`,
  `“Okay..., here we go,” he said, striking a pose again.`,
  `BOOM! She opened her eyes and felt the sheep in her hands, but nothing was there—just the memory of it.`,
  `He Confused,  wondered what went wrong. `,
  `She again tighten her fists to hit him.`,
  `“Wait,..wait  Cho!” he laughed confusingly, trying to lighten the mood.`,
  `He tried another BOOM with his plate, making it disappear and reappear.`,
  `“It came back! Then why doesn't Kiki?”, he wondered.`,
  `They stared at each other, like heroes and villains in a movie poster, both quiet for three seconds.`,
  `Then they noticed a strange white figure between them.`,
  `They turned to see what it is `,
  `it was their sheep, looking sad at sky as if it had experienced world war and lost everything.`,
  `The boy felt little confused like "when did it come" while his sister rushed to hug the sheep  "kiki..you here?". But as she did, the sheep jumped over her, and she fell on her face, with the sheep stepping lightly on her head.`,
  `The boy laughed loudly....She got frustrated " what...", She tried to kick him,"laughing?....", but he stood up and walked away, not noticing her. She fell again, `,
  `the sheep  laughed at her.`,
  `“eat fast, cho, we gotta go before they start” he said loudly while he is walking towards the house. `,
  `“You pig!” she shouted at the sheep.`,
  `Somewhere nearby, a real pig looked confused, as if asking, “What,..what did I do?” while other pigs laughed,punching tomatoes.`,
  `SOME TIME PASSED`,
  `They walked along the edge of the forest,they are going to the village, both shouldering the bag, feeling the cold air. They could see their breath in the crisp, chilly weather.`,
  `“Big bro,” she started.`,
  ` “Mm”,He looked at her.`,
  `“Why were those kids scared of you?”`,
  `“Because I… am… a demon!” he said, pretending to be scary.`,
  `“Stop joking, big bro. Tell me.”`,
  `“I do not know.. `,
  ` What would you do if you see... Like.., an elephant with two legs and a creepy smile?” he asked.`,
  `“I’d beat it with my heavenly gifted arms!” she said, flexing her tiny arm, which is in the size of a sand from a null universe (obviously it doesn't exist) .`,
  `“Ooo, I’m scared,” he said playfully.`,
  `“Good,” she replied , not getting his joke,started  walking proudly.`,

  `"kids are always afraid of  big guys like me...",the boy ,imitating a monster`,
  `"i am not afraid of anyone",she gave a evily proud look`,
  `"See..They are not strong like you,....",the boy`,
  `"ooo",she exclaimed`,
  `"There will be more people today than any other day,..its going to be fun",the boy excited`,
  `"yes,yes,fireworks,candies,toys..  cant wait big bro",she excitedly,her eyes filled with fireworks ,candies and toys, drooling`,
  `"yeah yeah",he 😅 `,
  `"But",she said in a sad tone`,
  `"what cho",he `,
  `"i...i wanted to ask you something,big bro"`,
  `"what is it cho"`,
  `“They hate you, right, big bro? The  village people?”`,
  `"HATE??", who taught you these words?..`,
  `"i dont know,,... i think i heard someone talking...dont change the topic big bro...then ill forget again"`,
  `"whom did you heard"`,
  `"first  you answer me big bro....They hate you, right?",cho`,
  `“aaaa...mm.”`,
  `“then why do we go to the village every day?”`,
  `"Tooo.... Entertain them",the boy `,
  `"athaa why?,big brooo....whats in it for you?..i dont understand...they dont even know who is behind the mask..we dont know who they are.....all i now know is that they hate you",she said,looked at his bag,there is a mask`,
  `"thats ONE good question",the boy 😅 but in his mind "why does she talk like grown person"`,
  `"tell me .big bro"`,
  `"That…....yeah i never told told you,right?...huhh…..Those people... /takes a breath/... they’re working hard,you know, having a tough day. Though they seem joyful, I can see that they feel empty ,maybe i can only see that. They want something to ease their emptiness  and....i think I am that something. I don't mind if they hate me or..or..anything—I just want them to have a really peaceful life, as long as I'm alive.”`,
  `even that person who hit you today?`,
  `even that person who hit me today`,
  `  they hurt you, they hate you,but you  want  them  to be  happy ,,,,,, ,,you re soo cool, big bro,  she admired her brother`,
  `"not only me cho,you should be like that too........that aside ..why did you ask me this in the first place",the boy`,
  `"sometimes i feel like someone's talking to me big bro",she said (not heard what he just said)`,
  // `“oooo”,she exclaimed in admiration`,
  `"BAMMM!" She crashed into him when he suddenly stopped walking`,
  `He stopped, looking at a burned-down PALACE(his home) far away, with a skeleton pinned on a post in front of it, he imagined as skeleton is smiling and waving at him.(now he didnt hear what she said)`,
  `“Big bro, hurry! We’re late!” she urged, noticing he was lost in thought.(she noticed Something off of him)`,
  `They kept walking, the forest getting colder as they got closer to the village.`,
  `Both started shaking in the cold breeze, unable to speak clearly.(which is unusual)`,
  `“Big bro,” Cho started.`,
  `“Mmmmmmmm?”`,
  `“When are we going to the city?” Cho asked in a quiet, sad tone.`,
  `“Soon, Cho.”`,
  `“How soon?”`,

  `“Very so--...wait......,whyyyyy?...you  have any friends there?.....is that friend "THAT  SOMEONE" you  eavesdropped  talking?",he asked funnily suspiously🤨`,
  `"no no...not that........................................i  dont want to be with people who hate my big bro...i hate them"`,
  `He shocked to hear that`,
  `"No cho,,..no!!..i told you,,it doesnt matter whether they hate me or u or both of us...we dont hate anyone",he said firmly`,
  `She looked at him `,
  `what do we do?",he asked`,
  `"But i dont like those village people hate you big bro",cho`,
  `what do we do?",he asked again`,
  `"What do we do?",she asked him as she dont know what to say`,
  `"weeee.. help them...okay..we just help them.....got it?",he said`,
  `"But!!",she hesitated"`,
  `"No BUT',,you got it?"`,
  `"Got it ,big bro",she saluted`,
  `Now she is wondering what she just did (wondering about saluting as she has never seen someone saluting)`,
  `"Do you know why i want to go to the city cho?",he started ,while walking with serious face`,
  `"im tired....im tired of thinking..that im the reason you dont have any friends...thats why i want to go to the city..if i can go,i can take you with me and you will find new people,new friends who dont know me there  and you  will have a better life than here......but no matter what happens we dont do things to people what they do to us.....we dont hate people..  ..okay...i knew you fear talk to village peoples but i never knew you hate them.."`,
  `Cho's eyes literally started spinning as her brain cant handle that much words`,
  `"i dont want you to hate anyone..for that i'll get you to the city real soon. Even if I can't go, I'll find a way to get you there.”`,
  `“No... I'll only go with you.”,she firmly said, literally ignored other words`,
  `The boy looked at her,"she just heard only the last sentence" written on the boy's face, then he smiled, and nodded, realizing he couldn't change her mind`,
  ``,
  `… `,
  `They walked some distance`,
  `As they get closer to the village, the cold starts to freeze them.`,
  `Suddenly the forest starting fill with smoke `,
  `
    “It’s really cold today ,   unsually, right, Cho?” he asked.
    `,
  `She didn’t respond.`,
  `He felt that she Stopped walking`,
  `He turned to see why she was quiet. She stood frozen,shaking in fear, staring at a scary BEAST, `,
  `The BEAST stood behind him,it was right infront of him but he didnt see it, he didnt felt its presence and now only he felt it was close.he got ready to fight it. Suddenly, he turned around and was shocked to see it looked like the creature he had described—"an elephant with two legs and a creepy smile."`,
  `He watched as it reached for him,he couldn't move as he is in fear,confused as he dont know what is happening. In its claws, it held a woman half of her body inside its mouth(NOT SPLITTEN) and asking for help.
    ****that  woman was That Red Saree.****`,
  `"brow.. boy",The Red Saree Woman struggled`,
  `the boy broke as he watched That Red Saree Woman Who Was nice to him getting eaten..... ,“Cho, run!” he yelled.`,
  `He was ready to attack, but before he could move, the BEAST jumped over him, showing its sharp claws and grinning as it flew toward cho.`,
  `“Chooooo!”`,
  `THE END`,
  `The driver was watching all this while hidden in the bushes from certain meters away,shaking in fear`,
  `"whats with these THREE beasts",he feared`,
  // `-----THREE????....could be his hallucinations--------`,
  `POST  CREDITS:`,
  `FUTURE (AFTER FEW  YEARS) `,
  `The city both The boy and cho badly wanted to go was in ruins and crowded, filled with laughter that seemed crazy compared to the sad reality underneath. On stage, a teen boy(THE  BOY ,cho's brother) knelt with his wrists in chains. He was badly hurt and covered in blood.`,
  `"I'm going to kill you... all of you," he said angrily. "I will" while the crowd chanted “ Kil him.. Kill him.. “`,
];
export default texts;
