const texts = [
  `INFORMATION on Planet ILO - it is a unique star where life thrives. Unlike Earth's sunrise and nightfall, Ilo experiences Risen and Fall.
    During Risen—the equivalent of night—the planet does not just grow dark. It glows with vibrant, aurora-like radiation. Every living being enlarges, except the Iloians (similar to humans on Earth). The wind smells like strawberry ice cream, and you can even see it with the naked eye. Imagine massive trees with colorful, glowing leaves, winds humming like melodies, and butterflies the size of humans. Its like a dreamlike paradise.
    Fall on Ilo is like Earth's day but far more mesmerizing. Everywhere you look, trees, flowers, and vibrant birds fill the landscape. In the dense forests, extraordinary creatures thrive. Picture a countryside brimming with farms, gardens, and forests under bright, warm weather, balanced perfectly by a cool, refreshing breeze. Its a harmonious, natural paradise.
    `,
  `Chapter 1: Light
    <div className="block">—---------------:-----------------------------------------::</div>
    PRESENT 
    `,
  `In a very dark space where no light could reach and no sound could be heard, there were floating rocks. In the distance, a planet shone like a light in the dark, the only light in the empty space. No other planets were nearby. 
    THE NAME OF THE PLANET-  ILO
    `,
  `Yet, in this silent, empty space, the laughter of a little girl could be heard. She illuminated the area with her bright smile, so bright it could outshine the sun. A beautiful black and blue butterfly sat on her head, gently moving its wings and adding to her joyful look. She was happily playing with her small sheep.`,
  `Twenty feet behind her`,
  `#/images/choIntro.jpg`,
  ` a boy , about fifteen years old, stood in a meadow filled with flowers and butterflies. He watched his sister laugh and play while trying to cut the last log from a pile of fifty trees. Even though he was tired, he felt joy seeing her so happy. 
    But his smile slowly faded as he noticed other kids playing together while his sister was alone.
    `,
  `#/images/TheBoyIntro.jpg`,

  `Far away from little girl. `,
  `people worked on their farms. A woman passed by, walking happily.`,
  `One of the farm women (P-1) called out:`,
  `P-1 (Woman): “Where did you buy this?”`,
  `The bywalker paused, confused.
    Bywalker (Woman): “What, sister?”
    `,
  `P-1: “Your saree.”`,
  `The bywalker smiled shyly.
    Bywalker: “This? My husband bought it. Why, sister? Does it look good?”
    `,
  `P-1: “It looks gorgeous!”`,
  `The bywalker beamed.
    Bywalker: “Really?”
    `,
  `Another woman (P-2) joined the conversation.`,
  `P-2: “Hey [bywalker’s name],Shall we go to the market later?”`,
  `Bywalker: “Why, sister?”`,
  `P-2: “I haven’t bought anything for the festival yet.”`,
  `Bywalker: “Oh,.....I do not know. I’ll come if I’m free. `,
  `Okay, sisters, my husband’s waiting. See you at the festival!”`,
  `With that, she ran off happily, flapping her hands, dancing, and smiling.`,
  `The two women watched her go, puzzled.
    P-1: “Who does she call her husband? She is not married, is she?”
    P-2: “Now that you mention it… I do not know.”
    Both stared at her, confused, and said in unison:
    Both: “Mental.”
    `,
  `The boy had been watching the scene from that far. He put down his axe and rushed toward the saree woman.`,
  `Boy: “Hey… hey, red sister!”`,
  `She stopped and turned.
    : “What is it, brown boy?”,
    `,
  `He caught his breath.
    Boy: “Where did you buy this?” he asked, pointing to her saree.
    `,
  `Bywalker: “My husband bought it from the city. Why?”`,
  `The boy’s face fell.
    Boy: “city? ”
    `,
  `He turned and started walking away.`,
  `Bywalker: “Wait.”`,
  `He stopped.
    Bywalker: “For whom?”
    `,
  `Boy: “My sister,” he replied, looking down.`,
  `Bywalker: “Do you have money?” she asked, smiling.`,
  `Boy: “Not enough to buy something like your dress,” he admitted.`,
  `Bywalker: “I’ll help you get what you want,” she said.`,
  `His face illuminated.
    Boy: “Really?”
    `,
  `Bywalker: “Only if you do something for me,” she added with a playful smirk.`,
  `Boy: “What do you want me to do? I can cut, I can break, I can… I can do anything!” he said, eager.`,
  `Bywalker: “wait wait!...Tomorrow, by this time, wait here. I’ll tell you then.”`,
  `Boy: “Yes!” he shouted, filled with joy.`,
  `He flew off like a happy mosquito (not literally flying).`,
  `As he ran, a bywalker woman walked along the path. Nearby, three women stood watching the
  bywalker woman talking to a boy.`,
  `“Why did you talk to him?” one of the women asked.`,
  `“Why? Shouldn&#39;t I talk to him?” the saree woman replied.`,
  `“He’s that devil’s kid,” another woman said.`,
  `“He?…” The woman glanced at the boy, who was running happily. “Doesn’t look like it to me,”
  she replied.`,
  `… … . … … ..`,
  `As he approached a pile of trees, he notices sunlight glinted off a car emerging from the forest, followed by a convoy of vehicles
    He face changed, 
    `,
  `"Cho, come on, it’s time to go. We can come back tomorrow," he called out.`,
  `"Nooo," she protested, looking at him sweetly.`,
  `"Okay, but do not blame me when the wolves come to take you away..." he joked, trying to scare her.`,
  `Before he could finish, she ran towards him.`,
  `"Haha, scaredy cat," he laughed.`,
  `Meanwhile, a man with a styled mustache, around 45, wearing sunglasses and a white shirt with dhotis, watched the boy collecting logs from one of the cars while scrolling on his phone.`,
  `"Who is that brat?" the man asked his driver.`,
  `“Who, boss?” the driver replied.`,
  `“That brat!” the man snapped.`,
  `"Him? You do not know him, boss?" the driver said with a hint of sarcasm`,
  `"Is he a fucking god ?" the man asked, annoyed as he took off his sunglasses.`,
  `"No, no, boss, I didn’t mean—" the driver stuttered.`,
  `Suddenly, the man kicked the driver out of the car.`,
  `"Go ask that brat what he’s doing on my fucking land," he ordered coldly.`,
  `The driver stood up, dusting off his shirt, glaring at the boy as if he were to blame. The driver’s eyes were filled with anger as he marched towards the boy.`,
  `"What are you doing here?" the driver shouted.`,
  `"Just collecting wood," the boy answered calmly.`,
  `"Do you know who owns this land?" the driver asked sharply.`,
  `The boy looked innocently confused.`,
  `"Where are you taking this?" the driver pushed.`,
  `"To Jehan boss," the boy replied, looking down.`,
  `(Jehan is the rival of THE MAN) `,
  `"What? Speak up, I didn’t hear you," the driver growled.`,
  `"To Jehan boss," the boy repeated, still looking down.`,
  `Anger flared in the driver’s eyes. “Bosss?!" he shouted, and then he hit the boy.`,
  `The boy fell to the ground.`,
  `“Boss? That jerk?!" the driver yelled,`,
  `Then the driver pointing his finger at the man in the car. "Look at him, He is the only bo—"" he started, but was cut off.`,
  `The man in the car gave a cold look that said, I’m the one .`,
  `The driver tried to speak, but a sharp sound interrupted him.`,
  `The driver yelped in pain and began to stagger around. He saw the cause of his pain: the little girl holding a stick, fury in her eyes.`,
  `"Don’t hurt my brother," she said firmly.`,
  `"you little brat,.." the driver growled.`,
  `She stared back at him with a fierce look.`,
  `“Who the hell are you? “, the driver growled. `,
  `
    As the driver moved toward her, the boy quickly stepped in. "Please, do not hurt my sister!" he pleaded. "You can hit me instead, but do not hurt her!" He held out the stick to the driver, his voice desperate.
    `,
  `The driver hesitated, looking at the stick, and slowly reached out to take it.`,
  `But just as he was about to grab it, a sudden loud sound scared him. He thought it was some kind of animal.`,
  `It was not. It was the man—standing half inside, half outside the car—laughing at them arrogantly, as if he owned the world.`,
  `"Come on, we need to meet “that boss”,’" the man said sarcastically, mocking the title.`,
  `"Yes, boss," the driver replied, flustered.`,
  `"If I see you here again, I do not know what I’ll do," the driver threatened, trying to scare the boy before going back to the car.`,
  `"If anyone sees that kid on my land again, cut them both up and feed them to Reema," the man ordered coldly.`,
  `"Yes, boss!" his men shouted together.`,
  `"Start the car, we’ve got work to do," the man commanded.`,
  `The boy’s eyes widened in fear, his heart racing. The anger in the little girl began to fade as her brother's tears softened her rage. She dropped the stick and hugged her brother tightly.`,
  `The cars sped away, their engines roaring, and among them was a truck that stood out. As it moved, the truck trembled ominously, as though some kind of beast was caged within. soon the sound of the engines faded into the distance`,
  `His sad face brightened as if nothing had happened.`,
  `See, Cho? They ran… cowards.Who are they messing with?" he joked, flexing his arms comically.`,
  `"You’re so cool, big bro!" she said, her eyes wide with admiration (not knowing he was pretending).`,
  `“Well, let's go, before those cowards return,” he said.`,
  `“Mmm, big bro,” she replied.`,
  `
    With nearly 50kg of wood logs balanced on his head, he began to move.
    `,
  `The nearby children, once joyful, suddenly fell silent as the boy and his sister walked past. The little girl waved at them cheerfully, smiling widely, but they looked scared, as if they had seen a ghost. Their eyes were fixed on the boy.`,
  `MEANWHILE IN THE CAR`,
  `“Well, who was that brat?” the man asked the driver while lighting up his cigar.`,
  `“You…” the driver started.`,
  `“You son of a…” the man picked up his gun from his hip pocket and pointed it at the driver.`,
  `“I’ll fucking gut you if you start with ‘You do not know, boss?’ again!” the driver snapped.`,
  `The driver side-eyed the gun, comically afraid.`,
  `“No, no, boss, I didn’t mean… I meant to say he is that devil’s kid. Don’t shoot me, boss!” the driver rushed to say, still fearful (comically).`,
  `“Oh,” the man said.`,
  `Suddenly, both the man and the driver realized the driver had taken his hands off the wheel in his panic.`,
  `Both looked at each other, shock written on their faces, and then screamed.The car started to tremble, descending into a moment of chaos.`,
  `SUDDEN FLIP CUT`,
  `After a little car-shaking moment, the driver’s face, which had earlier been like a tomato floating in water, now looked like it had been smashed by a punch from pigs.`,
  `The man wiped the driver’s bloodstains off his gun using a cloth torn from the driver’s clothes while the driver tended to his wounds, still driving.`,
  `“Mmm… what were you saying?” the man asked.`,
  `The driver looked at him but could not talk; his mouth was punctured.`,
  `
    “You dare to refuse my question?” the man said, glancing at his gun.
    `,
  `“Mmshdjsjd… Sjse,” the driver mumbled something unintelligible.`,
  `“Huhhh?” the man replied.`,
  `The driver looked at him again.`,
  `The man burst out laughing, almost choking on his amusement.`,
  `“Look at him, look at his stinky-ass nose!” the man exclaimed to the back seaters, still laughing.`,
  `“Come here, come here!” the man called to them. `,
  `“See?” he pointed at the driver’s nose.`,
  `They all laughed at the driver.`,
  `CAR STOPS`,
  `“What, you going to hit us”, the man joked. `,
  `“We’ve reached, boss,” the driver announced.`,
  `They all stopped laughing.`,
  `The man smirked.`,
  `“kK boys, get yo ass up,” the man shouted.`,
  `“It’s money-plucking time,” he murmured, scratching his butt.`,
  `TRUCK TREMBLES AGAIN`,
  `“Feed that goddamn beast, you useless sons of sons!” the man raged.`,
  `“Yes, boss,” they replied.`,
  `“mm..devil’s son, huh,” the man smirked.`,
  `CUT TO PAST (Years Ago)`,
  `The boy’s dad was a scientist. They lived in a palace-like home with a fountain at its center. Birds roamed freely inside, and a single tree near the fountain teemed with chirping birds. `,
  `The home was filled with the soothing sounds of nature.`,
  `It was the time of his first child’s arrival.`,
  `Palace workers chatted excitedly about the baby’s birth.`,
  `Worker 1: “Do you think this baby will live?”`,
  `Worker 2: “Who knows?”`,
  `Worker 3: “Even if it does not, they’re going to breed another one. Ha ha ha!” (cracked a joke).`,
  `Worker 4: “Shut up, idiot!” (bashed).`,
  `Worker 3: “What? Am I wrong?so far How many times? Five, right?”`,
  `Worker 4: “So?”Worker 3: “Nothing, just saying.”`,
  `Worker 4: “Don’t make fun of something like this. You’re a woman; you should be the last person to laugh at something like this.”`,
  `Worker 2: “How can you make fun of someone’s feelings? They fed you.”`,
  `Worker 1: “That too, Mr. [SCIENTIST’S NAME]’s family’s feelings.”`,
  `Worker 3: “Why are you all targeting me? I just—”`,
  `A strong cry of a baby interrupted the talk.`,
  `Worker 1: “The baby is born!”, excited`,
  `They ran up the stairs.`,
  `Inside the room, the scientist comforted his wife. Her face was filled with joy as she leaned against his chest. He held the baby in his arms, both unable to contain their happiness. The room was filled with warmth and light and birds and flies.`,
  `As the room glowed with happiness, the atmosphere outside changed abruptly. Darkness enveloped everything, and a heavy silence fell. Movements slowed, as if time had paused.`,
  `BLANK… EVERYTHING BLACKED OUT.`,
  `Suddenly, a hurricane came, not a normal one, a hurricane of dead souls swept through the house. These souls, with claws, reached out to grab everyone nearby. In the eye of the storm, the baby floated.`,
  `A SUDDEN CUT`,
  `Outside the palace, everything appeared normal.`,
  `Moments later, the inside of the palace was in ruins—blood splattered on the walls, claw marks everywhere, furniture destroyed, and birds broken and lifeless.`,
  `The scientist and his wife, injured and devastated, searched desperately for the baby.
    Finally, they found it in the center of the ruins.`,
  `Dead.
    `,
  `CUT 
    
    PRESENT. 
    Time: around 7:30
    `,
  `A strong wind blew through the air. It didn’t smell like just any wind; it smelled sweet, like strawberry ice cream. The wind was so powerful it could lift an adult off the ground. The world around looked bright and colorful, like a beautiful light show.`,
  `The entire world transformed into a magnificent light show, like the auroras of the northern pole, but spanning the entire planet. Sweetness filled the air, and the warmth of light rising from the ground was so captivating that even the blind or those without a sense of smell would be entranced. Every bird, tree, and insect—except humans—grew into towering giants.`,
  `While the world around him became brighter and larger, the boy’s own world shrank and dimmed as he returned home. There was nobody else. The house was not lively, but in the middle of a rundown, almost garbage-like house, he was cooking something delicious.`,
  `The battle between the scent of the food and the sweet fragrance of the world could shake the whole world.`,
  `He brought food to his little sister, who was sad and petting their sheep. When she smelled the food, her sad face illuminated with joy, and her eyes sparkled with happy tears.`,
  `“Areweryoue gmadsaat me, big brother?” she asked(blaffed), her mouth full of food and snorting a little.`,
  `“Haann?” he replied, confused but smiling.`,
  `“Are you mad at me?” she asked again, still sniffling.`,
  `“Eat slowly, Cho,” he said, tapping her head gently and giving her water.`,
  `While she drank, he looked at the sky. The clouds and asteroids looked colorful and beautiful, like a sea full of fish.`,
  `Suddenly, there was a loud noise, and he fell to the ground, dizzy and feeling like he had been knocked out.`,
  `His sister stood over him, holding a broomstick and smiling playfully. “Are you mad at me, big bro?” she asked.`,
  `“Uhh…,” he mumbled, still dizzy from the bump.`,
  `Then he jumped up, looking at her closely, and said, “I heard there’s going to be a fireworks festival” He started eating like nothing happened.`,
  `Her face suddenly went from angry to happy as she enjoyed his tasty food as if nothing had happened .`,
  `“Trrk trrk, here take this [boy's name]!” she called to her little sheep.`,
  `The boy looked surprised. “Really?” ah look`,
  `“What? I won’t give it to you! Bleh!” she teased.`,
  `“Ohh..I see,” he said,`,
  `Now he pose like he's going to  pull the sheep from the air magically.`,
  `He closed his eyes and—BOOM!—the sheep disappeared.`,
  `She isn't surprised. she just opened her arms, waiting for the sheep to come back, bouncing around and excited.`,
  `Nothing happened. She opened one eye and saw him eating calmly.`,
  `He began to sweat, feeling hot even in the cold night.`,
  `“Big... Brother,” she said in a funny, scary voice.`,
  `He turned slowly, sensing trouble as she looked at him like a  little monster.`,
  `“Okay, calm down, Cho. Why so serious?” he said with a confusingly smily face.`,
  `She turned back into her sweet self.`,
  `“Okay, here we go,” he said, striking a pose again.`,
  `BOOM! She opened her eyes and felt the sheep in her hands, but nothing was there—just the memory of it.`,
  `Confused, he wondered what went wrong. `,
  `She again tighten her fists to hit him.`,
  `“Wait, Cho!” he laughed, trying to lighten the mood.`,
  `He tried another BOOM with his plate, making it disappear and reappear.`,
  `“It came back! So why does not Kiki?” he wondered.`,
  `They stared at each other, like heroes and villains in a movie poster, both quiet for three seconds.`,
  `Then they noticed a strange white figure between them.`,
  `They turned to see what it is `,
  `it was their sheep, looking sad at sky as if it had experienced world war and lost everything.`,
  `The boy felt little confused while his sister rushed to hug the sheep. But as she did, the sheep jumped over her, and she fell on her face, with the sheep stepping lightly on her head.`,
  `The boy laughed loudly. She tried to kick him, but he stood up and walked away, not noticing her. She fell again, `,
  `the sheep  laughed at her.`,
  `“eat fast, cho, we gotta go before they start”he saidl loudly while he is walking towards the house. `,
  `“You pig!” she shouted at the sheep.`,
  `Somewhere nearby, a real pig looked confused, as if asking, “What,..what did I do?” while other pigs laughed.`,
  `TIME PASSED`,
  `They walked along the edge of the forest, both shouldering the bag, feeling the cold air. They could see their breath in the crisp, chilly weather.`,
  `“Big bro,” she started.`,
  ` “Mm”,He looked at her.`,
  `“Why were those kids scared of you?”`,
  `“Because I… am… a demon!” he said, pretending to be scary.`,
  `“Stop joking, big bro. Tell me.”`,
  `“I do not know.. `,
  ` What would you do if you saw... Like.., an elephant with two legs and a creepy smile?” he asked.`,
  `“I’d beat it with my heavenly gifted arms!” she said, flexing her tiny arm, which is in the size of a sand from a null universe (obviously it doesn't exist) .`,
  `“Ooo, I’m scared,” he said playfully.`,
  `“Good,” she replied, not getting his joke.`,
  `As they walked, she said, “They hate you, right, big bro? The whole village?”`,
  `“mm.”`,
  `“Then why do you go to the village every day?”`,
  `"That….huhh…..Those people... /takes a breath/... they’re working hard, having a tough day. Though they seem joyful, I can see that they feel empty . They want something to ease their emptiness  and I am that something. I don't mind if they hate me—I just want them to have a really peaceful life, as long as I'm alive.”`,
  `“You’re so cool, big bro!”`,
  `He stopped, looking at a burned-down building far away, with a skeleton pinned on a post in front of it.`,
  `“Big bro, hurry! We’re late!” she urged, noticing he was lost in thought.`,
  `They kept walking, the forest getting colder as they got closer to the village.`,
  `Both started shaking in the cold breeze, unable to speak clearly.`,
  `“Big bro,” Cho started.`,
  `“Mm?”`,
  `“When are we going to the city?” Cho asked in a quiet, sad tone.`,
  `“Soon, Cho.”`,
  `“How soon?”`,
  `“Very soon. Even if I can't go, I'll find a way to get you there.”`,
  `“No... I'll only go with you.”`,
  `The boy looked at her, smiled, and nodded, realizing he couldn't change her mind`,
  `… 
    “It’s really cold today, right, Cho?” he asked.
    `,
  `She didn’t answer.`,
  `He turned to see why she was quiet. She stood frozen, staring at a scary figure, shaking in fear.`,
  `The figure stood behind him, and he felt it was close. He got ready to fight it. Suddenly, he turned around and was shocked to see it looked like the creature he had described—an elephant with two legs and a creepy smile.`,
  `He watched as it reached for him, shaking with fear. In its claws, it held a woman half eaten and asking for help, in its mouth, there was blood,the woman was that red saree sister .`,
  `the boy broke ,“Cho, run!” he yelled.`,
  `He was ready to attack, but before he could move, the demon jumped over him, showing its sharp claws and grinning as it flew toward his sister.`,
  `“Chooooo!”`,
  `THE END`,
  `POST  CREDITS:`,
  `FUTURE  `,
  `The city was broken and crowded, filled with laughter that seemed crazy compared to the sad reality underneath. On stage, a boy(THE SAME BOY ) knelt with his wrists in chains. His face was hurt and covered in blood.`,
  `"I'm going to kill you... all of you," he said angrily. "I will make you feel my pain as you die.” while the crowd chanted “ Kil him.. Kill him.. “`,
];
export default texts;
